### ISSUE TITLE
Users should have unique usernames

### ISSUE THREAD

**Issue by tomekowal** [lambdaacademy/2015.01_elixir#13]
Currently interface allows adding more than one user with the same email and username. This results in crash, when signing in. Both email and username fields should be unique.

**Comment by ppikula** [comment]
I added uniqueness on the db level in the following commit 12ee41b57e1381bb3dc7388d0328682620bcdfb8, but I think it should be also tested on the controller level (Ecto throws exception when either email or username is not unique).
