### ISSUE TITLE
Enable rating talks by users and external API

### ISSUE THREAD

**Issue by tomekowal** [lambdaacademy/2015.01_elixir#4]
The API is actually up to us.
Users should not be able to vote more than once for given talk.

**Comment by pprzetacznik** [comment]
How authentication should be implemented? I found sth like this: https://github.com/edgurgel/signaturex but I don't consider this solution as very safe. What is application of this Swift app? Will it be used by organizers who will invite people to press smile faces on the tablet or this Swift app will be also available for conference participant?

**Comment by tomekowal** [comment]
The IPad will be held by conference organisers. The application will _not_ be available to download. We can skip the authentication and simply put the API under one common URL, which will be available only form internal private network.
To sum up: don't bother with authentication for the API, we will handle that by setting up nginx proxy. Only make sure, that the API is available under `/api/something`

**Comment by ppikula** [comment]
@pprzetacznik  I have a comment to the update function: https://github.com/lambdaacademy/2015.01_elixir/blob/master/web/controllers/talk_api_controller.ex#L15

I think It should be inside ecto transaction (https://hexdocs.pm/ecto/0.2.5/Ecto.Repo.html#transaction/2), 
because there is a possibility of race condition there.

**Comment by pprzetacznik** [comment]
@ppikula: please see last commit: https://github.com/lambdaacademy/2015.01_elixir/commit/934440dfe78f266047a1af8d9b66641e2ced9bc4 if this solution is sufficient for this problem.
